### ISSUE TITLE
Błędna autentykacja

### ISSUE THREAD

**Issue by baszczewski** [PayU-EMEA/openpayu_php#21]
Witam. Staram się wdrożyć Państwa API w moim aktualnym projekcie. Napotkałem jednak problem. 

``` php
$response = OpenPayU_Order::create($data);
```

Metoda zwraca błąd jeśli jako wartości pos_id oraz signature key (drugi klucz md5) podam dane swojego punktu płatności (Express Payment), zamiast wartości podanych w dokumentacji (145227 / 13a980d4f851f3d9a1cfc792fb1f5e50).

Przy podaniu moich danych zostaje zwrócony wyjątek: 

``` php
OpenPayU_Http::throwHttpStatusException($httpStatus, $result);
```

argumenty:

``` php
integer 401
object OpenPayU_Result(9) {
    private status => string(0) ""
    private error => string(0) ""
    private success => integer 0
    private request => string(0) ""
    private response => string(0) ""
    private sessionId => string(0) ""
    private message => string(0) ""
    private countryCode => string(0) ""
    private reqId => string(0) ""
}
```

Problem występuje zarówno na moim serwerze testowym jak i localhoscie.

**Comment by pawellab** [comment]
Witam
mam ten sam problem.
Korzystam z wtyczki PayU do Woocommerce pobranej z Waszej strony.
Gdzie się ustawia: Punkt Płatności jako Checkout. ?

**Comment by regdos** [comment]
Proszę o kontakt z zespołem wsparcia - tech@payu.pl
