### ISSUE TITLE
Dokumentacja - odbieranie powiadomień

### ISSUE THREAD

**Issue by baszczewski** [PayU-EMEA/openpayu_php#22]
Witam serdecznie. Mam prośbę o uszczegółowienie dokumentacji, jako że kilka zagadnień mogło by być przedstawione w precyzyjniejszy / obszerniejszy sposób:
1) Na jakim etapie zamówienie może być odrzucone przez sprzedawcę? Czy wykorzystanie do tego systemu powiadomień jest dobrym pomysłem? Czy mogę to zrobić wyłącznie dopóki status zamówienia ma wartość "pending"? Jak w takiej sytuacji powinna wyglądać odpowiedź dla usługi? Bieżący kod:

``` php

        try 
        {
            if (!empty($data)) 
            {
                $result = OpenPayU_Order::consumeNotification($data);
            }

            if ($result->getResponse()->order->orderId) 
            {
                /* Check if OrderId exists in Merchant Service, update Order data by OrderRetrieveRequest */
                $order = OpenPayU_Order::retrieve($result->getResponse()->order->orderId);
                $status_desc = OpenPayU_Util::statusDesc($order->getStatus());

                /* If exists return OrderNotifyResponse */
                $rsp = OpenPayU::buildOrderNotifyResponse($result->getResponse()->order->orderId);

                if (!empty($rsp)) 
                {
                    $this->response->headers('Content-type','application/json; charset='.Kohana::$charset);
                    $this->response->body($rsp);
                }
            }
        } 
        catch (OpenPayU_Exception $e) 
        {
            echo $e->getMessage();
        }
```

2) Czy po przekierowaniu na podstronę "completeUrl" mogę pobrać szczegóły dotyczące przetwarzanego zamówienia? Niestety w POST, ani GET nie znalazłem żadnych danych mi to umożliwiających. W przykładach również tego brakuje.

**Comment by gskgrek** [comment]
Mam podobny problem. Samo skierowanie na strone platnosici i dokonanie platnosci idzie bez problemu ale nie dostaje powiadomienia o zmianie status na testowym koncie :/

**Comment by adrian-kulig** [comment]
Witam, czy problem przedstawiony powyżej został rozwiązany ?

**Comment by regdos** [comment]
Proszę pamiętać, że adres do powiadomień musi być dostępny na publicznym adresie. Zachęcam do kontaktu z naszym BOK-iem w celu rozwiązania problemu.

**Comment by adrian-kulig** [comment]
Problem już został rozwiązany,

Serdecznie dziękuję za odpowiedź.

W dniu 17 stycznia 2017 19:25 użytkownik Tomasz Regdos <
notifications@github.com> napisał:
