### ISSUE TITLE
Nieprawidłowa sygnatura

### ISSUE THREAD

**Issue by xiio** [PayU-EMEA/openpayu_php#23]
Korzystam z kredencjałów testowych, próbuje dokonać testowej płatności. Jednak podczas odbierania pinga na "notifyUrl" otrzymuję wyjątek:

```
[exception.OpenPayU_Exception_Authorization] exception 'OpenPayU_Exception_Authorization' with message 'Invalid signature - 30984387705472f33cd723cce74eba03'  in vendor/openpayu/openpayu/lib/OpenPayU/OpenPayU.php:237
```

przed chwilą pobrałem paczkę z biblioteką więc mam najnowszą wersję.

**Comment by fronterweb** [comment]
@agnagna 
Witam,
zwracam się z tym samym problemem. 
Sytuacja jest identyczna jak w przypadku xiio

**Comment by bios-transspecies** [comment]
bliźniacza sprawa - tym razem problem przechodzi zamówienie ale komunikaty z potwierdzeniem zwracają błąd podczas OpenPayU_Order::consumeNotification()

php://input 

{"order":{"orderId":"PFDSVF2GXQ170330GUEST000P01","extOrderId":"fd67121506ab89673ea14ddc3f6c34a1","orderCreateDate":"2017-03-30T20:37:45.136+02:00","notifyUrl":"https://artmarketing.me/...","customerIp":"194.150.251.50","merchantPosId":"145227","description":"Future Knowledge MediaKit / 1 / ","currencyCode":"PLN","totalAmount":"18000","status":"PENDING","products":[{"name":"Future Knowledge MediaKit","unitPrice":"18000","quantity":"1"}]},"properties":[]}" 

vardump obiektu error

object(OpenPayU_Exception_Authorization)#12 (7) {  ["message":protected]=>  string(52) "Invalid signature - 4284f8f7ecacdbc795262186989d4c7d"  ["string":"Exception":private]=>  string(0) ""  ["code":protected]=>  int(0)  ["file":protected]=>  string(79) "/var/sites/a/artmarketing.me/vendor/openpayu/openpayu/lib/OpenPayU/OpenPayU.php"  ["line":protected]=>  int(36)  ["trace":"Exception":private]=>  array(4) {    [0]=>    array(6) {      ["file"]=>      string(79) "/var/sites/a/artmarketing.me/vendor/openpayu/openpayu/lib/OpenPayU/v2/Order.php"      ["line"]=>      int(159)      ["function"]=>      string(23) "verifyDocumentSignature"      ["class"]=>      string(8) "OpenPayU"      ["type"]=>      string(2) "::"      ["args"]=>      array(2) {  
................

**Comment by robertkrzuk** [comment]
@bios-transspecies Jak przesledzisz jak dziala ta funkcja to zobaczysz ze po drodze wyciaga dane z konfiguracji. Czy w akcji ktora wyrzuca ten blad wczytales ponownie konfiguracje?

`        OpenPayU_Configuration::setMerchantPosId($value_1);
        OpenPayU_Configuration::setSignatureKey($value_2);
        OpenPayU_Configuration::setOauthClientId($value3); 
        OpenPayU_Configuration::setOauthClientSecret($value4);client_secret`

**Comment by bios-transspecies** [comment]
robertkrzuk - ja nie pamiętam już w czym była rzecz ale sprawa jest już dawno zamknięta. dziękuję za odpowiedź, ale nawet ciężko mi potwierdzić w tej chwili jak to załatwiłem.

**Comment by cve** [comment]
Mam ten sam problem, tak tworzę zamówienie:

````json
{  
   "notifyUrl":"url...",
   "continueUrl":"url...",
   "customerIp":"194.28.34.20",
   "merchantPosId":"145227",
   "description":"Płatność za zakup pakietu Premium na miesiąc",
   "currencyCode":"PLN",
   "totalAmount":1499,
   "extOrderId":"5c8136d945f824.78091354",
   "buyer":{  
      "email":"test@example.com",
      "phone":"7777777777",
      "firstName":"test",
      "lastName":"",
      "language":"pl"
   },
   "products":[  
      {  
         "name":"Płatność za zakup pakietu Premium na miesiąc",
         "quantity":1,
         "unitPrice":1499
      }
   ]
}
````

takie dane otrzymuję w notify:

````json
{  
   "order":{  
      "orderId":"Z2P736PJDL190307GUEST000P01",
      "extOrderId":"5c8136d945f824.78091354",
      "orderCreateDate":"2019-03-07T16:20:57.730+01:00",
      "notifyUrl":"<url...>",
      "customerIp":"194.28.34.20",
      "merchantPosId":"145227",
      "description":"Płatność za zakup pakietu Premium na miesiąc",
      "currencyCode":"PLN",
      "totalAmount":"1499",
      "buyer":{  
         "customerId":"guest",
         "email":"test@example.com",
         "phone":"7777777777",
         "firstName":"test",
         "language":"pl"
      },
      "payMethod":{  
         "amount":"1499",
         "type":"PBL"
      },
      "status":"COMPLETED",
      "products":[  
         {  
            "name":"Płatność za zakup pakietu Premium na miesiąc",
            "unitPrice":"1499",
            "quantity":"1"
         }
      ]
   },
   "localReceiptDateTime":"2019-03-07T16:21:04.828+01:00",
   "properties":[  
      {  
         "name":"PAYMENT_ID",
         "value":"1300995681"
      }
   ]
}
````

ale razem z tymi danymi mam wyjątek:

````
Uncaught PHP Exception OpenPayU_Exception_Authorization: "Invalid signature - 96c7123c2382c040dd9bee07c841068a"
````

korzystam z dokumentacji i testowej płatności produkcyjnej. Do obsługi PayU mam klasę opakowującą openpayu i konfigurację w konstruktorze, więc przy wywoływaniu notify na pewno konfiguracja jest ustawiana ponownie

**Comment by cve** [comment]
@agnagna czy możesz pomóc?

**Comment by regdos** [comment]
@cve - agnagna nie jest już pracownikiem PayU.

Sprawdziłem Pana notyfikację przy użyciu https://github.com/PayU/openpayu_php/blob/master/examples/v2/order/OrderNotify.php i podpis jest wyliczany poprawnie i zgadza się z tym w nagłówku PayU więc problem leży po stronie Pana kodu. 

PS. Proszę na przyszłość zgłaszać nowy błąd a nie otwierać stary.

**Comment by piotrknapik** [comment]
Dla wszystkich zagubionych dusz, które tu trafiły — zanim zaczniecie walidować sygnaturę zgodnie z przykładem powyżej, upewnijcie się, że konfiguracja jest załadowana. Niestety, biblioteka nie rzuca błędem, że 'signature key is empty'.

`OpenPayU_Configuration::setSignatureKey(<wasz klucz>);`
itd.

Mnie pomogło.
