### ISSUE TITLE
PayU first send a new status to merchant site and then saves it by himself

### ISSUE THREAD

**Issue by Karpol** [PayU-EMEA/openpayu_php#71]
When I get a notification I use the "Retrieve" method instead of "consumeNotification".
I noticed that PayU first send a new status to merchant site and then saves it by himself.
In request, the order status is COMPLETED but the "Retrieve" method still returns the previous status.
PayU expects HTTP status 200 and stops sending notifications. 
As a result the payment is done but in my application the status is still "Pending".

**Comment by urgotto** [comment]
It is look like system have 2 types of statuses. Status that indicate a order creation (from Retrieve->getStatus) and status that shows order state (from consumeNotification, probably). Any way Retrieve contain both of them, but required is deeper - $response->getResponse()->orders[0]->status
