### ISSUE TITLE
Retrieve order - data not found

### ISSUE THREAD

**Issue by apsg** [PayU-EMEA/openpayu_php#72]
I'm trying to retrieve order details using `\OpenPayU_Order::retrieve()` function. 

I'm passing valid orderID (checked in the web panel - it exists) but always getting exception:

```
OpenPayU_Exception_Network in Http.php line 98:
DATA_NOT_FOUND - Could not find data for given criteria.
in Http.php line 98
at OpenPayU_Http::throwHttpStatusException(404, object(OpenPayU_Result)) in Order.php line 196
at OpenPayU_Order::verifyResponse(array('code' => 404, 'response' => '{"status":{"statusCode":"DATA_NOT_FOUND","severity":"INFO","statusDesc":"Could not find data for given criteria."}}'), 'OrderRetrieveResponse') in Order.php line 83
at OpenPayU_Order::retrieve('103_5950d83b95c03') in web.php line 117
```

How can I get the order details properly using orderId?

**Comment by adriano66** [comment]
It seems like the orderID you specified doesn't exist - it got removed or is invalid.

IIRC transaction ID (PAYMENT_ID) in the PayU dashboard is not order ID, or I'm missing something and you actually can get PayU orderID somewhere from the dashboard - I'd happily get to know where ^^

Anyway, I'm just saving orderID I get from the `PayU OpenPayU_Order::create()` response to DB so I can use the `OpenPayU_Order::retrieve()` method later.


```
$response = OpenPayU_Order::create($orderData);
$paymentResponse = $response->getResponse();

// $paymentResponse->extOrderId // Local orderID - Order id in your shop
// $paymentResponse->orderId // PayU orderID - save this, use this

$getOrderDetails = OpenPayU_Order::retrieve($paymentResponse->orderId)->getResponse()->orders[0];
```
`retrieve()` method docblock [states the same](https://github.com/PayU/openpayu_php/blob/master/lib/OpenPayU/v2/Order.php#L65)

> @param string $orderId PayU OrderId sent back in OrderCreateResponse


Where [orderID](http://developers.payu.com/en/restapi.html#order_data_retrieve) is something like ['LDLW5N7MF4140324GUEST000P01'](http://developers.payu.com/en/restapi.html#update_notification_for_order_status) while transaction ID (PAYMENT_ID) in the web panel is just some integer number
