### ISSUE TITLE
Wyświetlenie notifyURL

### ISSUE THREAD

**Issue by mindasolutions** [PayU-EMEA/openpayu_php#88]
Witam,
Mam problem z obsługą integracji z parametru "notifyURL". Skrypt ma przekierowywać na płatności PayU po uzupełnieniu formularza. Po kliknięciu prześlij wywołuje się następująca funkcja:

`function minda_payu_get_form($form = null){
        global $wpdb; 

        $wpdb->hide_errors();
        var_dump($form);
        echo "testowo";

        if(!empty($form)){
        	$extOrderId = time();
            $sql = 'INSERT INTO `'.$wpdb->prefix.'certyfikaty` (`extOrderId`, `name`, `nip`, `address`, `email`, `craft`, `description`, `type_certyficate`, `www`, `phone`, `customer_name`) VALUE ("'.$extOrderId.'", "'.$form['job_title'].'", "'.$form['job_nip'].'", "'.$form['job_location'].'", "'.$form['application'].'", "'.implode(" ",$form['job_category']).'", "'.$form['job_description'].'", "'.$form['cerr'].'", "'.$form['company_website'].'", "'.$form['phone'].'", "'.$form['imieinazyw'].'")';
            $result = $wpdb->query($sql);

            minda_make_payment($form['job_title'], $form['application'], $form['phone'], $form['imieinazyw'], $extOrderId);
        }

        $sql = 'SELECT * FROM '.$wpdb->prefix.'certyfikaty';
    }`

`function minda_make_payment($company_name, $email, $phone, $client_name, $extOrderId){
        require_once 'lib/openpayu.php';
        
        //set Environment
        OpenPayU_Configuration::setEnvironment('secure');

        //set POS ID and Second MD5 Key (from merchant admin panel)
        OpenPayU_Configuration::setMerchantPosId('adadad'); // POS ID (pos_id) / OAuth protocol - client_id
        OpenPayU_Configuration::setSignatureKey('abcdfkfs'); // Second key (MD5)

        //set Oauth Client Id and Oauth Client Secret (from merchant admin panel)
        OpenPayU_Configuration::setOauthClientId('asdasdasd'); // OAuth protocol - client_id / POS ID (pos_id)
        OpenPayU_Configuration::setOauthClientSecret('adadada'); // Key (MD5) / OAuth protocol - client_secret 

        /* path for example files*/
        $dir = explode(basename(dirname(__FILE__)) . '/', $_SERVER['SCRIPT_NAME']);
        $directory = $dir[0] . basename(dirname(__FILE__));
        $url = ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? 'https://' : 'http://') . $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . $dir[0];

        define('HOME_DIR', $url);
        define('EXAMPLES_DIR', HOME_DIR . 'examples/');

        $client_name = explode(" ", $client_name);
        $order['continueUrl'] = HOME_DIR.'/success'; //customer will be redirected to this page after successfull payment
            $order['notifyUrl'] = HOME_DIR.'/noticeurl';
            $order['customerIp'] = $_SERVER['REMOTE_ADDR'];
            $order['merchantPosId'] = OpenPayU_Configuration::getMerchantPosId();
            $order['description'] = 'Opłata za weryfikację firmy';
            $order['additionalDescription'] = $company_name;
            $order['currencyCode'] = 'PLN';
            $order['totalAmount'] = 4900;
            $order['extOrderId'] = $extOrderId; //must be unique!

            $order['products'][0]['name'] = 'Opłata za weryfikację firmy';
            $order['products'][0]['unitPrice'] = 4900;
            $order['products'][0]['quantity'] = 1;

            //optional section buyer
            $order['buyer']['email'] = $email;
            $order['buyer']['phone'] = $phone;
            $order['buyer']['firstName'] = $client_name[0];
            $order['buyer']['lastName'] = $client_name[1];

            $response = OpenPayU_Order::create($order);

            header('Location:'.$response->getResponse()->redirectUri); //You must redirect your client to PayU payment summary page.

    }`

Natomiast w notifyURL wywoływana jest następująca funkcja:

`function minda_payu_recive_order($data){
    					require_once 'lib/openpayu.php';
    					

    					//set Environment
    	        OpenPayU_Configuration::setEnvironment('secure');

    	        //set POS ID and Second MD5 Key (from merchant admin panel)
    	        OpenPayU_Configuration::setMerchantPosId('adsadda'); // POS ID (pos_id) / OAuth protocol - client_id
    	        OpenPayU_Configuration::setSignatureKey('adsassad'); // Second key (MD5)

    	        //set Oauth Client Id and Oauth Client Secret (from merchant admin panel)
    	        OpenPayU_Configuration::setOauthClientId('adadasd'); // OAuth protocol - client_id / POS ID (pos_id)
    	        OpenPayU_Configuration::setOauthClientSecret('asdadasdadas'); // Key (MD5) / OAuth protocol - client_secret 

    					if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    					    $body = file_get_contents('php://input');
    					    $data = trim($body);
    					    try {
    					        if (!empty($data)) {
    					            $result = OpenPayU_Order::consumeNotification($data);
    					        }
    					        if ($result->getResponse()->order->orderId) {
    					            /* Check if OrderId exists in Merchant Service, update Order data by OrderRetrieveRequest */
    					            $order = OpenPayU_Order::retrieve($result->getResponse()->order->orderId);
    					                $sql = 'UPDATE `'.$wpdb->prefix.'certyfikaty` SET `status` = '.$order->getStatus().' WHERE `extOrderId` = '.$result->getResponse()->order->extOrderId;
    					                $result = $wpdb->query($sql);
    					            if($order->getStatus() == 'SUCCESS'){
    					                //the response should be status 200
    					                header("HTTP/1.1 200 OK");

    					            }
    					        }
    					    } catch (OpenPayU_Exception $e) {
    					        echo $e->getMessage();
    					    }
    					    exit;
    					}
    }`

Chciałbym po testowej płatności zmienić status konkretnego zamówienia w bazie danych. Skrypt zachowuje się tak, jakby do notifyURL nie docierały żadne informacje.

**Comment by regdos** [comment]
Czy testy są prowadzone na publicznie dostępnym serwisie?
