### ISSUE TITLE
Does the TLS1.2 change for curl affects the SDK? Does the sdk need an upgrade?

### ISSUE THREAD

**Issue by razvan-tache** [PayU-EMEA/openpayu_php#89]

**Comment by peterpp** [comment]
I found out that it is not possible to open SSL connection from server which use TLS 1.0 by default. So I have to force curl to use 1.2. My pull request: https://github.com/PayU/openpayu_php/pull/101

**Comment by regdos** [comment]
https://github.com/PayU-EMEA/openpayu_php/commit/3ae6f3f1d882c71cf6266d8ec34735dabd269218
