### ISSUE TITLE
Dziwne zachowanie w zależności od ceny

### ISSUE THREAD

**Issue by SoftSolid** [PayU-EMEA/openpayu_php#94]
Witam
Przy cenie produktu 53.99 i cenie łącznej za zamówienie 68.99 nie mogę przejść do płatności. Pojawia się biały ekran a po cofnięciu "ERROR_SYNTAX - Bad syntax". Jeśli zmienię cenę produktu na 70 przechodzi bez problemu do płatności. Jeśli dodam do koszyka inny produkt też nie ma tego problemu.
Proszę o sugestie w czym może być problem.

Pozdrawiam
Robert.

**Comment by regdos** [comment]
Problem dotyczy SDK czy któregoś pluginu?

**Comment by SoftSolid** [comment]
Piszemy nasz plugin do CS-Cart i zauważyliśmy takie dziwne zachowanie.
