### ISSUE TITLE
\OpenPayU_Order::consumeNotification($data)->getResponse() -  typ zwracanej wartości

### ISSUE THREAD

**Issue by nataniel** [PayU-EMEA/openpayu_php#99]
w klasie OpenPayU_Result jest:

```
/**
 * @access public
 * @return string
 */
public function getResponse()
```

Tymczasem w dokumentacji (https://github.com/PayU/openpayu_php/blob/master/examples/v2/order/OrderNotify.php) mamy:

```
$result = OpenPayU_Order::consumeNotification($data);
$result->getResponse()->order->orderId;
```

To w końcu jaka jest wartość zwracana przez getResponse() - string czy object?

**Comment by regdos** [comment]
https://github.com/PayU-EMEA/openpayu_php/commit/054181d5feda205ba4f308f3a81fb4a5228af57f
